import type { AppData } from "./types";

/** Default seed data — realistic placeholders, fully editable & persisted in localStorage. */
export const SEED: AppData = {
  sante: {
    kpis: [
      { id: "k1", label: "Sommeil", value: 7.2, target: 8, unit: "h", trend: "up", delta: 4 },
      { id: "k2", label: "Pas / jour", value: 8400, target: 10000, unit: "", trend: "up", delta: 12 },
      { id: "k3", label: "Récupération (HRV)", value: 68, target: 75, unit: "ms", trend: "flat", delta: 1 },
      { id: "k4", label: "Stress moyen", value: 38, target: 30, unit: "%", trend: "down", delta: -6 },
    ],
    projects: [
      {
        id: "p1",
        name: "Protocole sommeil",
        description: "Reconstruire un rythme circadien stable sur 30 jours.",
        status: "active",
        progress: 64,
        due: "2026-07-01",
        tags: ["sommeil", "routine"],
        tasks: [
          { id: "t1", label: "Couvre-feu écran 22h30", done: true },
          { id: "t2", label: "Lumière du matin 10 min", done: true },
          { id: "t3", label: "Pas de caféine après 14h", done: false },
        ],
      },
      {
        id: "p2",
        name: "Force & mobilité",
        description: "3 séances/semaine + mobilité quotidienne.",
        status: "active",
        progress: 41,
        due: "2026-09-01",
        tags: ["sport"],
        tasks: [
          { id: "t1", label: "Programme 3x/sem", done: true },
          { id: "t2", label: "Mobilité 10 min/jour", done: false },
        ],
      },
      {
        id: "p3",
        name: "Bilan biologique annuel",
        description: "Analyses sanguines complètes + interprétation.",
        status: "planned",
        progress: 0,
        tags: ["santé"],
        tasks: [{ id: "t1", label: "Prendre RDV labo", done: false }],
      },
    ],
  },
  finances: {
    kpis: [
      { id: "k1", label: "Patrimoine net", value: 184500, target: 250000, unit: "€", trend: "up", delta: 8 },
      { id: "k2", label: "Épargne / mois", value: 2100, target: 2500, unit: "€", trend: "up", delta: 5 },
      { id: "k3", label: "Taux d'épargne", value: 34, target: 40, unit: "%", trend: "flat", delta: 0 },
      { id: "k4", label: "Burn rate", value: 4050, target: 3800, unit: "€", trend: "down", delta: -3 },
    ],
    projects: [
      {
        id: "p1",
        name: "Fonds d'urgence 6 mois",
        description: "Atteindre 6 mois de dépenses en cash sécurisé.",
        status: "active",
        progress: 78,
        due: "2026-08-01",
        tags: ["sécurité"],
        tasks: [
          { id: "t1", label: "Ouvrir livret à 4%", done: true },
          { id: "t2", label: "Virement auto 600€/mois", done: true },
          { id: "t3", label: "Atteindre 24 000€", done: false },
        ],
      },
      {
        id: "p2",
        name: "Portefeuille long terme",
        description: "Allocation ETF World + obligations, rééquilibrage trimestriel.",
        status: "active",
        progress: 52,
        tags: ["invest"],
        tasks: [
          { id: "t1", label: "Définir allocation cible", done: true },
          { id: "t2", label: "DCA mensuel programmé", done: true },
          { id: "t3", label: "Rééquilibrer Q3", done: false },
        ],
      },
      {
        id: "p3",
        name: "Optimisation fiscale",
        description: "Revue PER / enveloppes fiscales avant fin d'année.",
        status: "planned",
        progress: 10,
        tags: ["fiscalité"],
        tasks: [{ id: "t1", label: "Simuler plafond PER", done: false }],
      },
    ],
  },
  business: {
    kpis: [
      { id: "k1", label: "MRR", value: 14200, target: 20000, unit: "€", trend: "up", delta: 11 },
      { id: "k2", label: "Clients actifs", value: 86, target: 120, unit: "", trend: "up", delta: 7 },
      { id: "k3", label: "Churn", value: 3.4, target: 2.5, unit: "%", trend: "down", delta: -0.6 },
      { id: "k4", label: "Marge brute", value: 72, target: 78, unit: "%", trend: "flat", delta: 1 },
    ],
    projects: [
      {
        id: "p1",
        name: "Lancement offre Pro",
        description: "Nouvelle gamme tarifaire + page de vente.",
        status: "active",
        progress: 58,
        due: "2026-06-30",
        tags: ["produit", "revenus"],
        tasks: [
          { id: "t1", label: "Grille tarifaire validée", done: true },
          { id: "t2", label: "Landing page", done: true },
          { id: "t3", label: "Séquence email", done: false },
        ],
      },
      {
        id: "p2",
        name: "Pipeline acquisition",
        description: "Industrialiser le canal contenu + outbound.",
        status: "active",
        progress: 35,
        tags: ["growth"],
        tasks: [
          { id: "t1", label: "Calendrier éditorial", done: true },
          { id: "t2", label: "Script outbound", done: false },
        ],
      },
      {
        id: "p3",
        name: "Tableau de bord ops",
        description: "Centraliser les KPIs temps réel.",
        status: "paused",
        progress: 20,
        tags: ["ops"],
        tasks: [{ id: "t1", label: "Connecter les sources", done: false }],
      },
    ],
  },
  travail: {
    kpis: [
      { id: "k1", label: "Heures focus / sem", value: 22, target: 28, unit: "h", trend: "up", delta: 9 },
      { id: "k2", label: "Tâches clôturées", value: 41, target: 50, unit: "", trend: "up", delta: 14 },
      { id: "k3", label: "Réunions / sem", value: 11, target: 8, unit: "", trend: "down", delta: -10 },
      { id: "k4", label: "Inbox zero", value: 3, target: 5, unit: "j", trend: "flat", delta: 0 },
    ],
    projects: [
      {
        id: "p1",
        name: "Refonte présentation Q3",
        description: "Deck stratégique pour le comité de direction.",
        status: "active",
        progress: 45,
        due: "2026-06-20",
        tags: ["livrable"],
        tasks: [
          { id: "t1", label: "Structure & message", done: true },
          { id: "t2", label: "Données chiffrées", done: false },
          { id: "t3", label: "Design final", done: false },
        ],
      },
      {
        id: "p2",
        name: "Système Deep Work",
        description: "Blocs de focus protégés + revue hebdo.",
        status: "active",
        progress: 70,
        tags: ["productivité"],
        tasks: [
          { id: "t1", label: "Blocs 90 min matin", done: true },
          { id: "t2", label: "Notifications coupées", done: true },
          { id: "t3", label: "Revue du vendredi", done: false },
        ],
      },
      {
        id: "p3",
        name: "Onboarding nouveau collègue",
        description: "Documentation et plan des 30 premiers jours.",
        status: "planned",
        progress: 0,
        tags: ["équipe"],
        tasks: [{ id: "t1", label: "Rédiger le guide", done: false }],
      },
    ],
  },
  skills: {
    kpis: [
      { id: "k1", label: "Compétences actives", value: 4, target: 6, unit: "", trend: "up", delta: 1 },
      { id: "k2", label: "Streak", value: 18, target: 30, unit: "j", trend: "up", delta: 20 },
      { id: "k3", label: "Heures / sem", value: 6.5, target: 8, unit: "h", trend: "flat", delta: 2 },
      { id: "k4", label: "Maîtrise moy.", value: 57, target: 80, unit: "%", trend: "up", delta: 6 },
    ],
    projects: [
      {
        id: "p1",
        name: "Maîtriser le prompt engineering",
        description: "Parcours IA généré : théorie + pratique délibérée.",
        status: "active",
        progress: 62,
        tags: ["IA"],
        tasks: [
          { id: "t1", label: "Patterns de prompting", done: true },
          { id: "t2", label: "Évaluation des sorties", done: true },
          { id: "t3", label: "Projet d'application", done: false },
        ],
      },
      {
        id: "p2",
        name: "Espagnol — niveau B2",
        description: "Répétition espacée + conversation IA quotidienne.",
        status: "active",
        progress: 38,
        tags: ["langue"],
        tasks: [
          { id: "t1", label: "500 cartes Anki", done: true },
          { id: "t2", label: "10 min conversation/jour", done: false },
        ],
      },
      {
        id: "p3",
        name: "Design systémique",
        description: "Comprendre les boucles et leviers complexes.",
        status: "planned",
        progress: 5,
        tags: ["pensée"],
        tasks: [{ id: "t1", label: "Lire les fondamentaux", done: false }],
      },
    ],
  },
  knowledge: {
    kpis: [
      { id: "k1", label: "Notes", value: 312, target: 400, unit: "", trend: "up", delta: 8 },
      { id: "k2", label: "Sources traitées", value: 47, target: 60, unit: "", trend: "up", delta: 5 },
      { id: "k3", label: "Connexions", value: 128, target: 200, unit: "", trend: "up", delta: 10 },
      { id: "k4", label: "Backlog lecture", value: 23, target: 10, unit: "", trend: "down", delta: -4 },
    ],
    projects: [
      {
        id: "p1",
        name: "Second cerveau (PARA)",
        description: "Structurer notes en Projets / Domaines / Ressources / Archives.",
        status: "active",
        progress: 55,
        tags: ["système"],
        tasks: [
          { id: "t1", label: "Migrer les notes existantes", done: true },
          { id: "t2", label: "Définir les domaines", done: true },
          { id: "t3", label: "Revue mensuelle", done: false },
        ],
      },
      {
        id: "p2",
        name: "Synthèses de lecture IA",
        description: "Résumés structurés + cartes de révision automatiques.",
        status: "active",
        progress: 30,
        tags: ["IA", "lecture"],
        tasks: [
          { id: "t1", label: "Pipeline d'import", done: true },
          { id: "t2", label: "Template de synthèse", done: false },
        ],
      },
      {
        id: "p3",
        name: "Veille hebdomadaire",
        description: "Curation et archivage des meilleures sources.",
        status: "active",
        progress: 48,
        tags: ["veille"],
        tasks: [{ id: "t1", label: "Sélectionner 5 sources/sem", done: true }],
      },
    ],
  },
  agents: {
    kpis: [
      { id: "k1", label: "Agents déployés", value: 5, target: 10, unit: "", trend: "up", delta: 2 },
      { id: "k2", label: "Tâches automatisées", value: 142, target: 250, unit: "", trend: "up", delta: 18 },
      { id: "k3", label: "Taux de succès", value: 94, target: 98, unit: "%", trend: "up", delta: 2 },
      { id: "k4", label: "Temps gagné / sem", value: 9, target: 15, unit: "h", trend: "up", delta: 12 },
    ],
    projects: [
      {
        id: "p1",
        name: "Agent veille & résumés",
        description: "Surveille les sources, résume et alerte chaque matin.",
        status: "active",
        progress: 80,
        tags: ["veille", "auto"],
        tasks: [
          { id: "t1", label: "Définir déclencheur 7h", done: true },
          { id: "t2", label: "Connecter les sources", done: true },
          { id: "t3", label: "Format de rapport", done: false },
        ],
      },
      {
        id: "p2",
        name: "Agent inbox triage",
        description: "Classe, priorise et propose des réponses aux emails.",
        status: "active",
        progress: 47,
        tags: ["email"],
        tasks: [
          { id: "t1", label: "Règles de classement", done: true },
          { id: "t2", label: "Garde-fous validation", done: false },
        ],
      },
      {
        id: "p3",
        name: "Agent reporting business",
        description: "Compile les KPIs et génère le rapport hebdo.",
        status: "planned",
        progress: 12,
        tags: ["reporting"],
        tasks: [{ id: "t1", label: "Lister les métriques", done: false }],
      },
    ],
  },
};
